from io import BytesIO
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


def add_heading(document, text, level=1):
    document.add_heading(text, level=level)


def add_paragraph(document, text):
    document.add_paragraph(text)


def add_dataframe_table(document, df, title=None):
    """
    Add a pandas dataframe to a Word document as a formatted table.
    """
    if title:
        document.add_heading(title, level=2)

    if df is None or df.empty:
        document.add_paragraph("No data available.")
        return

    table = document.add_table(rows=1, cols=len(df.columns))
    table.style = "Table Grid"

    header_cells = table.rows[0].cells
    for i, col in enumerate(df.columns):
        header_cells[i].text = str(col)

    for _, row in df.iterrows():
        cells = table.add_row().cells
        for i, value in enumerate(row):
            if value is None:
                cells[i].text = ""
            else:
                cells[i].text = str(value)

    document.add_paragraph("")


def generate_word_report(
    study_title,
    research_question,
    year_range,
    group1_label,
    group1_codes,
    group2_label,
    group2_codes,
    summary_df,
    stats_display_df,
    group1_top_dx,
    group2_top_dx,
    group1_top_body,
    group2_top_body,
    group1_disposition,
    group2_disposition,
    # Age group / proportion tables (added previous milestone)
    comparative_age_groups=None,
    group1_age_groups=None,
    group2_age_groups=None,
    group1_prop_summary=None,
    group2_prop_summary=None,
    # Manuscript text (added this milestone)
    abstract_text=None,
    methods_text=None,
):
    """
    Generate a Word report and return it as an in-memory BytesIO object.
    """

    document = Document()

    # Title
    title = document.add_heading(study_title or "NEISS Research Studio Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.add_paragraph("Generated by NEISS Research Studio v2")
    document.add_paragraph("")

    # Study details
    add_heading(document, "Study Details", level=1)

    add_paragraph(document, f"Study years: {year_range[0]}–{year_range[1]}")

    if research_question:
        add_paragraph(document, f"Research question: {research_question}")

    add_paragraph(document, f"{group1_label}: product code(s) {', '.join(map(str, group1_codes))}")
    add_paragraph(document, f"{group2_label}: product code(s) {', '.join(map(str, group2_codes))}")

    # ---- Draft Abstract (if provided) ----
    if abstract_text:
        add_heading(document, "Draft Abstract", level=1)
        # Split into paragraphs on blank lines
        for block in abstract_text.split("\n\n"):
            block = block.strip()
            if block:
                add_paragraph(document, block)

    # ---- Draft Methods (if provided) ----
    if methods_text:
        add_heading(document, "Draft Methods", level=1)
        for block in methods_text.split("\n\n"):
            block = block.strip()
            if block:
                add_paragraph(document, block)

    # Summary table
    add_dataframe_table(
        document,
        summary_df,
        title="Table 1. Summary Comparison"
    )

    # Statistical testing
    add_dataframe_table(
        document,
        stats_display_df,
        title="Table 2. Statistical Testing"
    )

    document.add_paragraph(
        "Note: Odds ratios compare Group 1 to Group 2. "
        "An odds ratio greater than 1 indicates the outcome was more common in Group 1. "
        "Chi-square testing was used unless expected cell counts were small, in which case Fisher exact testing was used."
    )

    # Diagnosis tables
    add_dataframe_table(
        document,
        group1_top_dx,
        title=f"Table 3. Top Diagnoses: {group1_label}"
    )

    add_dataframe_table(
        document,
        group2_top_dx,
        title=f"Table 4. Top Diagnoses: {group2_label}"
    )

    # Body part tables
    add_dataframe_table(
        document,
        group1_top_body,
        title=f"Table 5. Top Body Parts: {group1_label}"
    )

    add_dataframe_table(
        document,
        group2_top_body,
        title=f"Table 6. Top Body Parts: {group2_label}"
    )

    # Disposition tables
    add_dataframe_table(
        document,
        group1_disposition,
        title=f"Table 7. Disposition Breakdown: {group1_label}"
    )

    add_dataframe_table(
        document,
        group2_disposition,
        title=f"Table 8. Disposition Breakdown: {group2_label}"
    )

    # ---- New tables: proportion summaries with Wilson 95% CIs ----
    if group1_prop_summary is not None and not group1_prop_summary.empty:
        add_dataframe_table(
            document,
            group1_prop_summary,
            title=f"Table 9. Key Proportions with 95% CI: {group1_label}"
        )

    if group2_prop_summary is not None and not group2_prop_summary.empty:
        add_dataframe_table(
            document,
            group2_prop_summary,
            title=f"Table 10. Key Proportions with 95% CI: {group2_label}"
        )

    # ---- New tables: age group breakdowns ----
    if comparative_age_groups is not None and not comparative_age_groups.empty:
        add_dataframe_table(
            document,
            comparative_age_groups,
            title="Table 11. Age Group Comparison"
        )

    if group1_age_groups is not None and not group1_age_groups.empty:
        add_dataframe_table(
            document,
            group1_age_groups,
            title=f"Table 12. Age Group Breakdown: {group1_label}"
        )

    if group2_age_groups is not None and not group2_age_groups.empty:
        add_dataframe_table(
            document,
            group2_age_groups,
            title=f"Table 13. Age Group Breakdown: {group2_label}"
        )

    # Methods
    add_heading(document, "Methods Note", level=1)

    add_paragraph(
        document,
        "This report was generated using the National Electronic Injury Surveillance System "
        "(NEISS) dataset, operated by the U.S. Consumer Product Safety Commission (CPSC). "
        "Cases were identified by NEISS product code and filtered by the year range, age, sex, "
        "and narrative keyword criteria specified at the time of analysis. "
        "Sample case counts represent the number of NEISS records matching the selected filters. "
        "Weighted national estimates were calculated by summing individual case weights "
        "provided by CPSC when the weight variable was available."
    )

    add_paragraph(
        document,
        "Statistical comparisons were performed on unweighted sample counts. "
        "Survey-weighted inferential statistics (incorporating the NEISS Weight, Stratum, and PSU "
        "variables) were not applied; results should be interpreted as descriptive comparisons of "
        "the sample, not as design-adjusted national estimates. "
        "Researchers intending to publish inferential findings should validate results using "
        "appropriate survey-design methods."
    )

    add_paragraph(
        document,
        "For each binary outcome, proportions were compared between groups using chi-square testing. "
        "Fisher exact testing was substituted when any expected cell count was less than 5. "
        "Odds ratios (OR) and relative risks (RR) were calculated from the 2x2 contingency table "
        "with 95% confidence intervals derived using the log method. "
        "A Haldane-Anscombe continuity correction of 0.5 was applied to all cells when any cell "
        "count was zero. "
        "Odds ratios and relative risks greater than 1 indicate the outcome was more common in Group 1."
    )

    add_paragraph(
        document,
        "Wilson score 95% confidence intervals were computed for all reported proportions, "
        "including % Male, % Female, % Pediatric, % Adult, hospital admission rate, fracture rate, "
        "concussion rate, and anatomic region rates. "
        "The Wilson interval was chosen because it performs well near proportions of 0 and 1 "
        "and for moderate sample sizes, unlike the standard normal-approximation (Wald) interval."
    )

    add_paragraph(
        document,
        "Statistical significance is indicated in the Sig column: "
        "*** p < 0.001, ** p < 0.01, * p < 0.05, ns p >= 0.05. "
        "Rows flagged in the Warnings column (small n < 20, cell count < 5, or zero events in "
        "one group) should be interpreted with caution, as odds ratio and relative risk estimates "
        "may be unstable."
    )

    add_paragraph(
        document,
        "Age distributions were compared between groups using the Mann-Whitney U test "
        "(two-sided), a non-parametric test that does not assume normally distributed ages. "
        "Effect size for the age comparison was quantified using rank-biserial correlation "
        "(r = 1 - 2U / n1*n2), reported in the Effect size column. "
        "Values near 0 indicate a negligible effect; values of approximately +/-0.3 indicate "
        "a moderate effect; values of approximately +/-0.5 or greater indicate a large effect."
    )

    # Limitations
    add_heading(document, "Limitations", level=1)

    add_paragraph(
        document,
        "NEISS captures injuries presenting to participating emergency departments and may not represent "
        "injuries treated in outpatient settings, urgent care centers, athletic training rooms, or cases that did "
        "not seek medical care. Product codes identify associated consumer products but do not always establish "
        "causation. Narrative detail and coding practices may vary between cases."
    )

    # Save to memory
    file_stream = BytesIO()
    document.save(file_stream)
    file_stream.seek(0)

    return file_stream
